/*
 * Copyright (c) @CompanyNameMagicTag. 2023. All rights reserved.
 */
#ifndef LV_IMG_CACHE_MANAGER_H
#define LV_IMG_CACHE_MANAGER_H
/*********************
 *      INCLUDES
 *********************/
#include <stdio.h>
#include "lvgl.h"
#include "lv_img_buf.h"
#ifdef __cplusplus
extern "C" {
#endif
/**********************
 *      TYPEDEFS
 **********************/
 typedef struct {
    lv_img_dsc_t info;
    bool isLongTerm;
    bool isLoaded;
} LvImgCacheInfo;

static const uint32_t LV_INVALID_RES_ID = 0;
static const uint32_t LV_INVALID_DIR_ID = 0;
 /**********************
 * GLOBAL PROTOTYPES
 **********************/
/**
 * @brief  Init ImgCacheManager.
 */
void LvImgCacheManagerInit(void);

/**
 * @brief  Deinit ImgCacheManager.
 */
void LvImgCacheManagerDeinit(void);

/**
 * @brief  Load a single image resource file.
 * @param  path    Image resource path.
 * @param  isLongTerm    Whether cache this image in long term. i.e.,
 * when memory is not enough to cache a new image, cached images will be released using LRU algirithm,
 * and comply with the following priorities: short term cached images, and then long term image.
 * @return resId corresponding to the image resource.
 */
uint32_t LvLoadImg(const char* path, bool isLongTerm);

/**
 * @brief  Load all images from a packed resource file.
 * @param  path    Image resource file path, which could not be NULL.
 * @param  fp    Pointer to FILE struct. If this parameter is not NULL, it will be used to process the resource file.
 * @param  offset    Number of bytes to offset from beginning of file. This parameter is used when fp is not NULL.
 * @param  isLongTerm    whether cache images in long term.
 * @return Return a dirId which is used to specify the packed resource images as a whole.
 */
uint32_t LvLoadAllFromFile(const char* path, FILE* fp, uint32_t offset, bool isLongTerm);

/**
 * @brief  Load a image from a packed resource file.
 * @param  resId    Image resource Id, which is generated by image tool.
 * @param  path    Image resource file path, which could not be NULL.
 * @param  fp    Pointer to FILE struct. If this parameter is not NULL, it will be used to process the resource file.
 * @param  offset    Number of bytes to offset from beginning of file. This parameter is used when fp is not NULL.
 * @param  isLongTerm    whether cache image in long term.
 * @return Return a resId which is used to specify the image.
 */
uint32_t LvLoadOneFromFile(uint32_t resId, const char* path, FILE* fp, uint32_t offset, bool isLongTerm);

/**
 * @brief  Load all images in a packed format from given buffer.
   These images should be unloaded manually by LvUnloadImg or LvUnloadImgsByDirId.
 * @param  buf    Address of the buffer, which stores images in a packed format.
 * @return Return a dirId which is used to specify the packed resource images as a whole.
 */
uint32_t LvLoadAllFromBuf(const uint8_t* buf);

/**
 * @brief  Get a valid image resId by a dirId.
 * @param  resId    Image resource Id, which is generated by image tool.
 * @param  dirId    Returned by LvLoadAllFromFile or LvLoadAllFromBuf.
 * @return Return a resId which is used to specify the image.
 */
uint32_t LvGetOneFromLoadedRes(uint32_t resId, uint32_t dirId);

/**
 * @brief  Unload a image with a unique resId.
 * @param  resId    Image resource Id, which is returned by other API.
 * @return Return whether the image is unloaded.
 */
bool LvUnloadImg(uint32_t resId);

/**
 * @brief  Unload images which are specified by given dirId.
 * @param  dirId    DirID, which is returned by other loading API.
 * @return Return whether this operation is executed successfully.
 */
bool LvUnloadImgsByDirId(uint32_t dirId);

/**
 * @brief  Unload all images which are cached in the specific term.
 * Images loaded by LvLoadAllFromBuf will not be unloaded.
 * @param  isLongTerm    Whether cache in long term.
 * @return Return whether images are unloaded.
 */
bool LvUnloadImgsByTerm(bool isLongTerm);

/**
 * @brief  Fill a pointer to LvImgCacheInfo struct by resId.
 * @param  resId    Image resource Id, which is returned by other API.
 * @param  imgCacheInfo    Pointer to LvImgCacheInfo struct.
 * @return Return whether this operation is executed successfully.
 */
bool LvGetImgCacheInfoById(uint32_t resId, LvImgCacheInfo* imgCacheInfo);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif