/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * Description: UIResouceFlashlight
 * Create: 2025-04-24
 */

#ifndef UI_RESOURCE_FLASHLIGHT_H
#define UI_RESOURCE_FLASHLIGHT_H

namespace OHOS {
static const int IMAGE_FLASHLIGHT_BLINKBUTTON = 0x100001;
static const int IMAGE_FLASHLIGHT_BLINKITEM = 0x100002;
static const int IMAGE_FLASHLIGHT_COLORITEM = 0x100003;
static const int IMAGE_FLASHLIGHT_COLOR_DARK_BLUE_BUTTON = 0x100004;
static const int IMAGE_FLASHLIGHT_COLOR_DARK_BLUE_PRESSBUTTON = 0x100005;
static const int IMAGE_FLASHLIGHT_COLOR_GREEN_BUTTON = 0x100006;
static const int IMAGE_FLASHLIGHT_COLOR_GREEN_PRESSBUTTON = 0x100007;
static const int IMAGE_FLASHLIGHT_COLOR_LIGHT_BLUE_BUTTON = 0x100008;
static const int IMAGE_FLASHLIGHT_COLOR_LIGHT_BLUE_PRESSBUTTON = 0x100009;
static const int IMAGE_FLASHLIGHT_COLOR_MULTI_BUTTON = 0x10000a;
static const int IMAGE_FLASHLIGHT_COLOR_MULTI_PRESSBUTTON = 0x10000b;
static const int IMAGE_FLASHLIGHT_COLOR_ORANGE_BUTTON = 0x10000c;
static const int IMAGE_FLASHLIGHT_COLOR_ORANGE_PRESSBUTTON = 0x10000d;
static const int IMAGE_FLASHLIGHT_COLOR_PURPLE_BUTTON = 0x10000e;
static const int IMAGE_FLASHLIGHT_COLOR_PURPLE_PRESSBUTTON = 0x10000f;
static const int IMAGE_FLASHLIGHT_COLOR_RED_BUTTON = 0x100010;
static const int IMAGE_FLASHLIGHT_COLOR_RED_PRESSBUTTON = 0x100011;
static const int IMAGE_FLASHLIGHT_COLOR_WHITE_BUTTON = 0x100012;
static const int IMAGE_FLASHLIGHT_COLOR_WHITE_PRESSBUTTON = 0x100013;
static const int IMAGE_FLASHLIGHT_COLOR_YELLOW_BUTTON = 0x100014;
static const int IMAGE_FLASHLIGHT_COLOR_YELLOW_PRESSBUTTON = 0x100015;
static const int IMAGE_FLASHLIGHT_DOWNARROW = 0x100016;
static const int IMAGE_FLASHLIGHT_FLASHLIGHTON = 0x100017;
static const int IMAGE_FLASHLIGHT_PLAY_BLACK_PAGE = 0x100018;
static const int IMAGE_FLASHLIGHT_PLAY_DARK_BLUE_PAGE = 0x100019;
static const int IMAGE_FLASHLIGHT_PLAY_GREEN_PAGE = 0x10001a;
static const int IMAGE_FLASHLIGHT_PLAY_LIGHT_BLUE_PAGE = 0x10001b;
static const int IMAGE_FLASHLIGHT_PLAY_MULTI_PAGE = 0x10001c;
static const int IMAGE_FLASHLIGHT_PLAY_ORANGE_PAGE = 0x10001d;
static const int IMAGE_FLASHLIGHT_PLAY_PURPLE_PAGE = 0x10001e;
static const int IMAGE_FLASHLIGHT_PLAY_RED_PAGE = 0x10001f;
static const int IMAGE_FLASHLIGHT_PLAY_WHITE_PAGE = 0x100020;
static const int IMAGE_FLASHLIGHT_PLAY_YELLOW_PAGE = 0x100021;
static const int IMAGE_FLASHLIGHT_RECOVERBUTTON = 0x100022;
static const int IMAGE_FLASHLIGHT_RECOVERCANCLE = 0x100023;
static const int IMAGE_FLASHLIGHT_RECOVERCONFIRM = 0x100024;
static const int IMAGE_FLASHLIGHT_RIGHTARROW = 0x100025;
}  // OHOS
#endif  // UI_RESOURCE_FLASHLIGHT_H
