/**
 * @defgroup    crypt_algid crypt_algid.h
 * @ingroup     crypto
 * @copyright   Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 * @brief       通用类型对外接口
 */

#ifndef CRYPT_ALGID_H
#define CRYPT_ALGID_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * @ingroup  crypt_algid
 * RAND 算法ID
 */
typedef enum {
    CRYPT_RAND_SHA1 = 0,
    CRYPT_RAND_SHA224,
    CRYPT_RAND_SHA256,
    CRYPT_RAND_SHA384,
    CRYPT_RAND_SHA512,
    CRYPT_RAND_HMAC_SHA1,
    CRYPT_RAND_HMAC_SHA224,
    CRYPT_RAND_HMAC_SHA256,
    CRYPT_RAND_HMAC_SHA384,
    CRYPT_RAND_HMAC_SHA512,
    CRYPT_RAND_AES128_CTR,
    CRYPT_RAND_AES192_CTR,
    CRYPT_RAND_AES256_CTR,
    CRYPT_RAND_AES128_CTR_DF,
    CRYPT_RAND_AES192_CTR_DF,
    CRYPT_RAND_AES256_CTR_DF,
    CRYPT_RAND_ALGID_MAX
} CRYPT_RAND_AlgId;

/**
 * @ingroup  crypt_algid
 * 哈希算法ID
 */
typedef enum {
    CRYPT_MD_MD4 = 0,
    CRYPT_MD_MD5,
    CRYPT_MD_SHA1,
    CRYPT_MD_SHA224,
    CRYPT_MD_SHA256,
    CRYPT_MD_SHA384,
    CRYPT_MD_SHA512,
    CRYPT_MD_SHA3_224,
    CRYPT_MD_SHA3_256,
    CRYPT_MD_SHA3_384,
    CRYPT_MD_SHA3_512,
    CRYPT_MD_SHAKE128,
    CRYPT_MD_SHAKE256,
    CRYPT_MD_SM3,
    CRYPT_MD_MAX
} CRYPT_MD_AlgId;

/**
 * @ingroup  crypt_algid
 * MAC算法ID
 */
typedef enum {
    CRYPT_MAC_HMAC_MD5 = 0,
    CRYPT_MAC_HMAC_SHA1,
    CRYPT_MAC_HMAC_SHA224,
    CRYPT_MAC_HMAC_SHA256,
    CRYPT_MAC_HMAC_SHA384,
    CRYPT_MAC_HMAC_SHA512,
    CRYPT_MAC_HMAC_SM3,
    CRYPT_MAC_CMAC_AES128,
    CRYPT_MAC_CMAC_AES192,
    CRYPT_MAC_CMAC_AES256,
    CRYPT_MAC_GMAC_AES128,
    CRYPT_MAC_GMAC_AES192,
    CRYPT_MAC_GMAC_AES256,
    CRYPT_MAC_SIPHASH64,
    CRYPT_MAC_SIPHASH128,
    CRYPT_MAC_MAX
} CRYPT_MAC_AlgId;

/**
 * @ingroup  crypt_algid
 * 非对称算法ID
 */
typedef enum {
    CRYPT_PKEY_DSA = 0,
    CRYPT_PKEY_ED25519,
    CRYPT_PKEY_X25519,
    CRYPT_PKEY_RSA,
    CRYPT_PKEY_DH,
    CRYPT_PKEY_ECDSA,
    CRYPT_PKEY_ECDH,
    CRYPT_PKEY_SM2,
    CRYPT_PKEY_ED448,
    CRYPT_PKEY_X448,
    CRYPT_PKEY_SM9,
    CRYPT_PKEY_MAX
} CRYPT_PKEY_AlgId;

/**
 * @ingroup  cipher_algid
 * 对称加解密模式组合算法ID
 */
typedef enum {
    CRYPT_CIPHER_AES128_CBC = 0,
    CRYPT_CIPHER_AES192_CBC,
    CRYPT_CIPHER_AES256_CBC,

    CRYPT_CIPHER_AES128_CTR,
    CRYPT_CIPHER_AES192_CTR,
    CRYPT_CIPHER_AES256_CTR,

    CRYPT_CIPHER_AES128_ECB,
    CRYPT_CIPHER_AES192_ECB,
    CRYPT_CIPHER_AES256_ECB,

    CRYPT_CIPHER_AES128_XTS,
    CRYPT_CIPHER_AES256_XTS,

    CRYPT_CIPHER_AES128_CCM,
    CRYPT_CIPHER_AES192_CCM,
    CRYPT_CIPHER_AES256_CCM,

    CRYPT_CIPHER_AES128_GCM,
    CRYPT_CIPHER_AES192_GCM,
    CRYPT_CIPHER_AES256_GCM,

    CRYPT_CIPHER_CHACHA20_POLY1305,

    CRYPT_CIPHER_SM4_CBC,
    CRYPT_CIPHER_SM4_ECB,

    CRYPT_CIPHER_AES128_CFB,
    CRYPT_CIPHER_AES192_CFB,
    CRYPT_CIPHER_AES256_CFB,

    CRYPT_CIPHER_AES128_OFB,
    CRYPT_CIPHER_AES192_OFB,
    CRYPT_CIPHER_AES256_OFB,
    
    CRYPT_CIPHER_TDES_ECB,
    CRYPT_CIPHER_TDES_CBC,
    CRYPT_CIPHER_TDES_OFB,
    CRYPT_CIPHER_TDES_CFB,

    CRYPT_CIPHER_SM4_CTR,
    CRYPT_CIPHER_SM4_GCM,

    CRYPT_CIPHER_MAX,
} CRYPT_CIPHER_AlgId;

/**
 * @ingroup  crypt_algid
 * 非对称算法参数ID，高16位为算法标识，低16位映射对应算法LowLevel的ID定义
 */
typedef enum {
    CRYPT_DH_RFC2409_768,
    CRYPT_DH_RFC2409_1024,
    CRYPT_DH_RFC3526_1536,
    CRYPT_DH_RFC3526_2048,
    CRYPT_DH_RFC3526_3072,
    CRYPT_DH_RFC3526_4096,
    CRYPT_DH_RFC3526_6144,
    CRYPT_DH_RFC3526_8192,
    CRYPT_DH_RFC7919_2048,
    CRYPT_DH_RFC7919_3072,
    CRYPT_DH_RFC7919_4096,
    CRYPT_DH_RFC7919_6144,
    CRYPT_DH_RFC7919_8192,
    CRYPT_ECC_NISTP224,
    CRYPT_ECC_NISTP256,
    CRYPT_ECC_NISTP384,
    CRYPT_ECC_NISTP521,
    CRYPT_ECC_SM2,
    CRYPT_ECC_SM9,
    CRYPT_ECC_PARAID_MAX,
    CRYPT_PKEY_PARAID_MAX
} CRYPT_PKEY_ParaId;

/**
 * @ingroup  crypt_algid
 * 椭圆曲线点编码格式
 */
typedef enum {
    CRYPT_POINT_COMPRESSED,
    CRYPT_POINT_UNCOMPRESSED, // 默认格式
    CRYPT_POINT_HYBRID,
    CRYPT_POINT_MAX
} CRYPT_PKEY_PointFormat;

/**
 * @ingroup  crypt_algid
 * KDF算法ID
 */
typedef enum {
    CRYPT_KDF_SCRYPT = 0,
    CRYPT_KDF_PBKDF2,
    CRYPT_KDF_KDFTLS12,
    CRYPT_KDF_HKDF,
    CRYPT_KDF_MAX
} CRYPT_KDF_AlgId;

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // CRYPT_ALGID_H
