#===============================================================================
# @brief    cmake file
# Copyright (c) @CompanyNameMagicTag 2022-2022. All rights reserved.
#===============================================================================
add_subdirectory(common)
add_subdirectory(egl)
add_subdirectory(vg)
add_subdirectory(hdf)
