/*
 * Copyright (c) @CompanyNameMagicTag. 2023. All rights reserved.
 */

#include "lv_demo_img_cache_manager.h"
#include <stdio.h>
#include "lv_img_ext.h"
#include "lv_demo_ext.h"
#include "lv_img_cache_manager.h"
#if LV_USE_DEMO_IMG_CACHE_MANAGER

static bool g_isInited = false;

// ResId generated by image tool
static const int BTN_ALARM = 0x100001;
static const int BTN_BRI_SCREEN = 0x100002;
static const int BTN_DN_DISTURB = 0x100003;
static const int BTN_FIND_PHONE = 0x100004;
static const int CLOCKELEMENT_HOURHAND = 0x200001;
static const int CLOCKELEMENT_MAIN_FACE_IMAGE = 0x200002;
static const int CLOCKELEMENT_MEDCIRCLE_IMAGE_PATH = 0x200003;
static const int CLOCKELEMENT_MINUTEHAND = 0x200004;
static const int CLOCKELEMENT_SECONDHAND = 0x200005;
static const int COUNTDOWN_IMAGE_07 = 0x300001;
static const int COUNTDOWN_IMAGE_13 = 0x300002;
static const int COUNTDOWN_IMAGE_18 = 0x300003;
static const int COVERFLOW_KALEIDOSCOPE = 0x400001;
static const int COVERFLOW_PLANET = 0x400002;
static const int COVERFLOW_RAINBOW = 0x400003;
static const int VOICE_ASSISTANT_55 = 0x500001;
static const int VOICE_ASSISTANT_56 = 0x500002;
static const int VOICE_ASSISTANT_57 = 0x500003;

#define BTN_RES_CNT 4
static uint32_t g_btnResId[BTN_RES_CNT] = {
    BTN_ALARM, BTN_BRI_SCREEN, BTN_DN_DISTURB, BTN_FIND_PHONE
};

#define CLOCKELEMENT_RES_CNT 5
static uint32_t g_clockelementResId[CLOCKELEMENT_RES_CNT] = {
    CLOCKELEMENT_HOURHAND, CLOCKELEMENT_MAIN_FACE_IMAGE, CLOCKELEMENT_MEDCIRCLE_IMAGE_PATH,
    CLOCKELEMENT_MINUTEHAND, CLOCKELEMENT_SECONDHAND
};

#define COUNTDOWN_RES_CNT 3
static uint32_t g_countdownResId[COUNTDOWN_RES_CNT] = {
    COUNTDOWN_IMAGE_07, COUNTDOWN_IMAGE_13, COUNTDOWN_IMAGE_18
};

#define COVERFLOW_RES_CNT 3
static uint32_t g_coverflowResId[COVERFLOW_RES_CNT] = {
    COVERFLOW_KALEIDOSCOPE, COVERFLOW_PLANET, COVERFLOW_RAINBOW
};

#define VOICE_RES_CNT 3
static uint32_t g_voiceResId[VOICE_RES_CNT] = {
    VOICE_ASSISTANT_55, VOICE_ASSISTANT_56, VOICE_ASSISTANT_57
};

#define DIR_ID_MAX_CNT 50
static uint32_t g_cachedDirId[DIR_ID_MAX_CNT] = {0};
static uint32_t g_cachedDirCnt = 0;
#define RES_ID_MAX_CNT 50
static uint32_t g_cachedResId[RES_ID_MAX_CNT] = {0};
static uint32_t g_cachedResCnt = 0;

static uint8_t* ReadDataToBuf(const char* path)
{
    FILE* fp = fopen(path, "rb");
    if (fp == NULL) {
        return NULL;
    }
    (void)fseek(fp, 0, SEEK_END);
    uint32_t fileLen = (uint32_t)ftell(fp);
    uint8_t* tempBuf = lv_mem_alloc(fileLen);
    (void)fseek(fp, 0, SEEK_SET);
    (void)fread(tempBuf, 1, fileLen, fp);
    (void)fclose(fp);
    return tempBuf;
}

static void CreateImgByResId(lv_obj_t* par, uint32_t resId)
{
    lv_obj_t* img = LvImgExtCreate(par);
    LvImgSetSrcById(img, resId);
}

static bool LoadAllFromLoadedRes(lv_obj_t* par, uint32_t* resIds, uint32_t cnt, uint32_t dirId)
{
    if (dirId == LV_INVALID_DIR_ID) {
        return false;
    }
    for (uint32_t i = 0; i < cnt; i++) {
        uint32_t resId = LvGetOneFromLoadedRes(resIds[i], dirId);
        CreateImgByResId(par, resId);
    }
    return true;
}

static void LoadAllFromBuf(lv_obj_t* par, const char* path, uint32_t* resIds, uint32_t cnt)
{
    uint8_t* buf = ReadDataToBuf(path);
    uint32_t dirId = LvLoadAllFromBuf(buf);
    lv_mem_free(buf);
    if (!LoadAllFromLoadedRes(par, resIds, cnt, dirId)) {
        printf("fail to LoadAllFromLoadedRes: %s\n", path);
        return;
    }
    g_cachedDirId[g_cachedDirCnt++] = dirId;
}

static void LoadOneFromFile(lv_obj_t* par, const char* path, uint32_t* resIds, uint32_t cnt)
{
    uint32_t resId = LvLoadOneFromFile(resIds[cnt - 1], path, NULL, 0, false);
    if (resId == LV_INVALID_RES_ID) {
        printf("fail to LoadOneFromFile: %s\n", path);
        return;
    }
    CreateImgByResId(par, resId);
    g_cachedResId[g_cachedResCnt++] = resId;
}

static void LoadAllFromFile(lv_obj_t* par, const char* path, uint32_t* resIds, uint32_t cnt)
{
    uint32_t dirId = LvLoadAllFromFile(path, NULL, 0, false);
    if (!LoadAllFromLoadedRes(par, resIds, cnt, dirId)) {
        printf("fail to LoadAllFromLoadedRes: %s\n", path);
        return;
    }
    g_cachedDirId[g_cachedDirCnt++] = dirId;
}

static void LoadAllFromFp(lv_obj_t* par, const char* path, uint32_t* resIds, uint32_t cnt)
{
    FILE* fp = fopen(path, "rb");
    if (fp == NULL) {
        printf("fail to open file: %s\n", path);
        return;
    }
    uint32_t dirId = LvLoadAllFromFile(path, fp, 0, false);
    (void)fclose(fp);
    if (!LoadAllFromLoadedRes(par, resIds, cnt, dirId)) {
        printf("fail to LoadAllFromLoadedRes: %s\n", path);
        return;
    }
    g_cachedDirId[g_cachedDirCnt++] = dirId;
}

static void LoadOneFromFp(lv_obj_t* par, const char* path, uint32_t* resIds, uint32_t cnt)
{
    FILE* fp = fopen(path, "rb");
    if (fp == NULL) {
        printf("fail to open file: %s\n", path);
        return;
    }
    uint32_t resId = LvLoadOneFromFile(resIds[cnt - 1], path, fp, 0, false);
    (void)fclose(fp);
    if (resId == LV_INVALID_RES_ID) {
        printf("fail to LvLoadOneFromFile: %s\n", path);
        return;
    }
    CreateImgByResId(par, resId);
    g_cachedResId[g_cachedResCnt++] = resId;
}

void LvDemoImgCacheManager(lv_obj_t* par)
{
    lv_obj_set_style_pad_all(par, 50, 0); // 50: padding
    lv_obj_set_flex_flow(par, LV_FLEX_FLOW_ROW_WRAP);

    LoadAllFromBuf(par, "/user/res/Btn.bin", &g_btnResId, BTN_RES_CNT);
    LoadAllFromFile(par, "/user/res/ClockElement.bin", &g_clockelementResId, CLOCKELEMENT_RES_CNT);
    LoadOneFromFile(par, "/user/res/ClockElement.bin", &g_clockelementResId, CLOCKELEMENT_RES_CNT);
    LoadOneFromFile(par, "/user/res/CountDown.bin", &g_countdownResId, COUNTDOWN_RES_CNT);
    LoadAllFromFile(par, "/user/res/CountDown.bin", &g_countdownResId, COUNTDOWN_RES_CNT);

    LoadOneFromFp(par, "/user/res/CoverFlow.bin", &g_coverflowResId, COVERFLOW_RES_CNT);
    LoadAllFromFp(par, "/user/res/CoverFlow.bin", &g_coverflowResId, COVERFLOW_RES_CNT);
    LoadAllFromFp(par, "/user/res/Voice.bin", &g_voiceResId, VOICE_RES_CNT);
    LoadOneFromFp(par, "/user/res/Voice.bin", &g_voiceResId, VOICE_RES_CNT);
}

static void Init(lv_obj_t* par)
{
    if (g_isInited) {
        return;
    }
    g_isInited = true;
    LvDemoImgCacheManager(par);
}

static void UnloadImgByDirId(void)
{
    for (uint32_t i = 0; i < g_cachedDirCnt; i++) {
        LvUnloadImgsByDirId(g_cachedDirId[i]);
        g_cachedDirId[i] = 0;
    }
    g_cachedDirCnt = 0;
}

static void UnloadImgsByResId(void)
{
    for (uint32_t i = 0; i < g_cachedResCnt; i++) {
        LvUnloadImg(g_cachedResId[i]);
        g_cachedResId[i] = 0;
    }
    g_cachedResCnt = 0;
}

static void UnloadImgsByTerm(void)
{
    LvUnloadImgsByTerm(true);
    LvUnloadImgsByTerm(false);
    memset_s(g_cachedResId, sizeof(g_cachedResId), 0, sizeof(g_cachedResId));
    g_cachedResCnt = 0;
    memset_s(g_cachedDirId, sizeof(g_cachedDirId), 0, sizeof(g_cachedDirId));
    g_cachedDirCnt = 0;
}

static void Deinit(lv_obj_t* par)
{
    if (!g_isInited) {
        return;
    }
    lv_obj_clean(par);

    UnloadImgByDirId();
    UnloadImgsByResId();
    UnloadImgsByTerm();
    g_isInited = false;
}

static LvTestCaseInfo g_testCaseInfo = {
    "ImgCacheManager",
    Init,
    Deinit,
};

void LvRegisterDemoImgCacheManager(void)
{
    RegisterTestCase(&g_testCaseInfo);
}
#endif
