#!/usr/bin/env python3
# encoding=utf-8
# ============================================================================
# @brief    build system entry, receive param & start to build
# Copyright (c) CompanyNameMagicTag 2022-2022. All rights reserved.
# ============================================================================
"""
接收参数列表及解释:
    -c:
        clean后编译
    -j:
        -j<num>, 以num线程数编译
        默认为机器最大线程数
    -def=:
        -def=XXX,YYY,ZZZ=x,...  向本次编译target中添加XXX、YYY、ZZZ=x编译宏
        可使用-def=-:XXX 来屏蔽XXX宏
        可使用-def=-:ZZZ=x 来添加或者修改ZZZ宏
    -component=:
        -component=XXX,YYY,...  仅编译XXX,YYY组件
    -ninja:
        使用ninja生成中间文件
        默认使用Unix makefile
    -[release/debug]:
        debug:     在生成反汇编文件时信息更加全面但也更耗时
        release:   在生成反汇编文件时节省时间
        默认为debug
    -dump:
        输出target的编译参数
    -nhso:
        不更新HSO数据库
    -out_libs:
        -out_libs=file_path, 不再链接成elf, 转而将所有.a打包成一个大的.a
    -project=:
        指定项目名称（默认：MyProject）
    -version=:
        指定版本号（默认：1.0.0）
    others:
        作为匹配编译target_names的关键字
"""
import os
import sys
import shutil
import datetime  # 新增日期模块

# 遍历当前目录下的所有文件和文件夹
for file_name in os.listdir("."):
    # 如果找到了CMakeLists.txt.sdk文件
    if file_name == "CMakeLists.txt.sdk":
        # 将文件名修改为CMakeLists.txt
        shutil.move("CMakeLists.txt", "CMakeLists.txt.simulator")
        shutil.move(file_name, "CMakeLists.txt")
from distutils.spawn import find_executable

sys.dont_write_bytecode = True
root_dir = os.path.split(os.path.realpath(__file__))[0]
sys.path.append(os.path.join(root_dir, 'build', 'config'))
sys.path.append(os.path.join(root_dir, 'build', 'script'))

# 新增版本参数解析 -------------------------------------------------
project_name = "T553"  # 默认项目名
version_num = "1.2.1"       # 默认版本号
compile_date = datetime.datetime.now().strftime("%Y%m%d")

# 处理-project和-version参数
filtered_argv = []
i = 0
while i < len(sys.argv):
    arg = sys.argv[i]
    if arg.startswith("-project="):
        project_name = arg.split("=", 1)[1]
    elif arg.startswith("-version="):
        version_num = arg.split("=", 1)[1]
    else:
        filtered_argv.append(arg)
    i += 1
sys.argv = filtered_argv  # 更新参数列表

# 生成version.h文件 -------------------------------------------------
version_header = f"""\
#ifndef WATCH_VERSION_H
#define WATCH_VERSION_H

/* Auto-generated by build system - DO NOT EDIT */
#define VERSION_STRING "{project_name}_HV{version_num}_{compile_date}"

#endif // WATCH_VERSION_H
"""

version_path = os.path.join(root_dir, 'vendor', 'sikey', 'drivers', "watch_version.h")
with open(version_path, "w") as f:
    f.write(version_header)
# -------------------------------------------------------------------

from cmake_builder import CMakeBuilder

def check_enviroment():
    if not find_executable("cmake"):
        print("cmake is not installed or not added to system path.")
    if not find_executable("ninja") and not find_executable("make"):
        print("make/ninja is not installed or not added to system path.")

check_enviroment()

builder = CMakeBuilder(sys.argv)

builder.build()
