/*
* Copyright (c) CompanyNameMagicTag. 2021-2021. All rights reserved.
* Description: source interfaces
* Author: Media Software Group
* Create: 2021-04-21
*/

#ifndef STREAM_CONFIG_H
#define STREAM_CONFIG_H

#include "audio_base_type.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

#define AUDIO_MOD_FOR_STORAGE 0XAD00
#define STREAM_TYPE_NUM AUDIO_STREAM_TYPE_HASH_ID_MAX
#define AUDIO_STREAM_INVALID_TYPE_HASH_ID AUDIO_STREAM_TYPE_HASH_ID_MAX

typedef enum {
    AUDIO_STREAM_ALARM_HASH_ID = 0,
    AUDIO_STREAM_ALARM_SYSTEM_HASH_ID,
    AUDIO_STREAM_ALARM_CLOCK_HASH_ID,
    AUDIO_STREAM_RING_HASH_ID,
    AUDIO_STREAM_VOICE_CALL_HASH_ID,
    AUDIO_STREAM_VOICE_CALL_VOIP_HASH_ID,
    AUDIO_STREAM_VOICE_CALL_BT_SCO_HASH_ID,
    AUDIO_STREAM_VOICE_CALL_VOLTE_HASH_ID,
    AUDIO_STREAM_VOICE_CALL_VOLTE_SPI_HASH_ID,
    AUDIO_STREAM_VOICE_ASSISTANT_HASH_ID,
    AUDIO_STREAM_TTS_HASH_ID,
    AUDIO_STREAM_NOTIFICATION_HASH_ID,
    AUDIO_STREAM_NOTIFICATION_SYSTEM_HASH_ID,
    AUDIO_STREAM_NOTIFICATION_PROMPT_HASH_ID,
    AUDIO_STREAM_MUSIC_HASH_ID,
    AUDIO_STREAM_A2DP_MUSIC_HASH_ID,
    AUDIO_STREAM_FITNESS_VIDEO_HASH_ID,
    AUDIO_STREAM_VOICE_RECORD_HASH_ID,
    AUDIO_STREAM_VOICE_RECOGNITION_HASH_ID,
    AUDIO_STREAM_TYPE_HASH_ID_MAX
} StreamTypeHashId;

typedef struct {
    AudioStreamType streamType;
    StreamTypeHashId typeId;
} StreamTypeVolume;

static StreamTypeVolume typeVolumes[STREAM_TYPE_NUM] = {
    {AUDIO_STREAM_ALARM, AUDIO_STREAM_ALARM_HASH_ID},
    {AUDIO_STREAM_ALARM_SYSTEM, AUDIO_STREAM_ALARM_SYSTEM_HASH_ID},
    {AUDIO_STREAM_ALARM_CLOCK, AUDIO_STREAM_ALARM_CLOCK_HASH_ID},
    {AUDIO_STREAM_RING, AUDIO_STREAM_RING_HASH_ID},
    {AUDIO_STREAM_VOICE_CALL, AUDIO_STREAM_VOICE_CALL_HASH_ID},
    {AUDIO_STREAM_VOICE_CALL_VOIP, AUDIO_STREAM_VOICE_CALL_VOIP_HASH_ID},
    {AUDIO_STREAM_VOICE_CALL_BT_SCO, AUDIO_STREAM_VOICE_CALL_BT_SCO_HASH_ID},
    {AUDIO_STREAM_VOICE_CALL_VOLTE, AUDIO_STREAM_VOICE_CALL_VOLTE_HASH_ID},
    {AUDIO_STREAM_VOICE_CALL_VOLTE_SPI, AUDIO_STREAM_VOICE_CALL_VOLTE_SPI_HASH_ID},
    {AUDIO_STREAM_VOICE_ASSISTANT, AUDIO_STREAM_VOICE_ASSISTANT_HASH_ID},
    {AUDIO_STREAM_TTS, AUDIO_STREAM_TTS_HASH_ID},
    {AUDIO_STREAM_NOTIFICATION, AUDIO_STREAM_NOTIFICATION_HASH_ID},
    {AUDIO_STREAM_NOTIFICATION_SYSTEM, AUDIO_STREAM_NOTIFICATION_SYSTEM_HASH_ID},
    {AUDIO_STREAM_NOTIFICATION_PROMPT, AUDIO_STREAM_NOTIFICATION_PROMPT_HASH_ID},
    {AUDIO_STREAM_MUSIC, AUDIO_STREAM_MUSIC_HASH_ID},
    {AUDIO_STREAM_A2DP_MUSIC, AUDIO_STREAM_A2DP_MUSIC_HASH_ID},
    {AUDIO_STREAM_FITNESS_VIDEO, AUDIO_STREAM_FITNESS_VIDEO_HASH_ID},
    {AUDIO_STREAM_VOICE_RECORD, AUDIO_STREAM_VOICE_RECORD_HASH_ID},
    {AUDIO_STREAM_VOICE_RECOGNITION, AUDIO_STREAM_VOICE_RECOGNITION_HASH_ID},
};

const char *typeName[] = {
    "aud_alarm",
    "aud_alarm_system",
    "aud_alarm_clock",
    "aud_ring",
    "aud_voice_call",
    "aud_voice_call_voip",
    "aud_voice_call_bt_sco",
    "aud_voice_call_volte",
    "aud_voice_assistant",
    "aud_tts",
    "aud_notif",
    "aud_notif_system",
    "aud_notif_prompt",
    "aud_music",
    "aud_fitness_video",
    "aud_voice_record",
    "aud_voice_recognition"
};

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif

